Milestone 3 Game logic
tongoonamujera/Tic-Tac-Toe pull request #4
Opened 2021-06-13 12:05 UTC by tongoonamujera

this milestone consists of real game logic

2021-06-19 21:43 UTC, george-shammar requested changes
### **STATUS:CHANGES REQUIRED** :recycle: :recycle: :construction: :construction_worker_man: 

Good Job tongoona. 

**Highlights**
Your repo looks professional with the correct workflow and README. :+1: 

Please see the required changes below as well as my inline comments.

- [ ] No puts/print and gets.chomp outside main.rb file. Your main.rb should be responsible for that. See my in-line comment in this regard.
- [ ] Your TicTacToe game crashes after asking for first player's name. The output is a "Loaderror". Cannot load "/game_board.rb". The file does not exist but you have required it in your code.

Since I was unable to check the behaviour of your game, the requirement for the behaviour of your game would be checked upon your next submission. 

Please submit another CRR when you're ready.

Cheers and happy coding. :smile:

2021-06-19 21:43 UTC, george-shammar commented on lib/game_player_helper.rb
> +
- [ ] No puts/print and gets.chomp outside main.rb file.

2021-06-21 01:54 UTC, BrianSammit requested changes
CHANGES REQUIRED :red_circle: :stop_sign: 
----------------
Hello @tongoonamujera, great job working on the required changes :muscle: :1st_place_medal: 
However, there are a few changes to make to complete this milestone :hammer_and_wrench: see them below :point_down: 
---------------------

- [ ] You have some validation for the names but the games continue if a keep input the same value. 
![Screenshot from 2021-06-20 20-48-00](https://user-images.githubusercontent.com/64173189/122696502-d2044a80-d208-11eb-8fff-071350c3463c.png)

Please fix this bug. 

- [ ] If a make a move that is already taken, on the next move put the same mark for the move.

![Screenshot from 2021-06-20 20-51-06](https://user-images.githubusercontent.com/64173189/122696674-3f17e000-d209-11eb-8e8b-9f6ef261e6a9.png)

- [ ] The game does not change the mark for the next player's move. 

![Screenshot from 2021-06-20 20-52-42](https://user-images.githubusercontent.com/64173189/122696764-7a1a1380-d209-11eb-8246-ccb312842576.png)

-----------------
Please fix these required changes and send it again for another review :muscle: 
HAPPY CODING!!!!

![200 (1)](https://user-images.githubusercontent.com/64173189/122696820-a170e080-d209-11eb-849b-6bf638695652.gif)

2021-06-21 21:12 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛑🛠**
Hi @tongoonamujera 👋🏽
You have done a great job so far but there are still some changes that must be done to have this milestone approved. Check it below 👇🏽

- [ ] As the previous TSE pointed out, the token of the next player does not change after his move. Kindly fix that.
   That's all. Just apply that change and request for another code review. Good luck and happy coding 👨🏽‍💻👨🏽‍💻.

2021-06-22 06:07 UTC, bini-i approved these changes
# Status: Approved :heavy_check_mark:          
### Hello @tongoonamujera   :wave: 

Thanks for working on the requirements by the previous reviewers, your project meets all the requirements and it is approved :tada: .
#### Highlights
- Methods are small and do one thing only, which makes your code easy to read and debug.
- Only one method(**winner?**) is used to check for winning cases, which makes your code DRY.
- Note: Make sure to look out for attr_accessor as it allows setting instance properties from outside the class, only use them when needed.

### Keep up the good work :+1: 

#### If you have any question feel free to ask within the PR and ping me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Code Reviewer)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)#

2021-06-22 17:11 UTC, merged